### ISSUE TITLE
I have an app that has certificate transparency failed, is there any script that I can use?

### ISSUE THREAD

**Issue by flamecopper** [httptoolkit/frida-interception-and-unpinning#79] opened 2024-03-18 03:08 UTC
`core.network.utils.NetworkThrowable.getMessage()
(agent) [831692] Backtrace:
	i06.f(DispatcherEventsReporter.kt:55)
	d06.g(Dispatcher.kt:69)
	d06.a(Dispatcher.kt:281)
	e06.invokeSuspend(Dispatcher.kt:13)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	tbj.t(CoroutineContext.kt:58)
	b2.resumeWith(AbstractCoroutine.kt:23)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:48)
	tbj.t(CoroutineContext.kt:58)
	b2.resumeWith(AbstractCoroutine.kt:23)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:48)
	a06.run(DispatchedTask.kt:116)
	d4b$a.run(LimitedDispatcher.kt:4)
	zbi.run(Tasks.kt:3)
	ga4$b.run(CoroutineScheduler.kt:101)

(agent) [831692] Return Value: Certificate transparency failed

I did this, while doing a objection method hooking with the expected return value.

**Comment by pimterry** [comment] 2024-03-19 11:45
Duplicate of #80 so let's discuss this there.

**Closed by pimterry** 2024-03-19 11:45 UTC
