### ISSUE TITLE
API of the APP brings up "Attention Required! | Cloudflare" with script

### ISSUE THREAD

**Issue by ItsMarcoDE** [httptoolkit/frida-interception-and-unpinning#102] opened 2024-08-02 17:45 UTC
Hello,

The APP "portaventura.android" has an interesting problem. When I start the APP without the interception-and-unpinning scripts, the APP works without any issues. However, when I start it with the scripts to access the API, I can see the API requests, but I encounter an error from Cloudflare everywhere: "Attention Required! | Cloudflare - Sorry, you have been blocked."

[frida.txt](https://github.com/user-attachments/files/16473603/frida.txt)

<img width="1635" alt="mitm" src="https://github.com/user-attachments/assets/eb0af71b-3a63-4d51-9f0b-77e149b533f2">

**Comment by pimterry** [comment] 2024-08-03 09:39
This is interesting but unrelated to certificate pinning & these scripts in this repo, which manage _client_ trust for intercepting traffic (so I will close this in a sec).

What's happening here is that the _server_ (not the client) is rejecting your traffic. That's almost certainly because the server is doing TLS fingerprinting (bit of a guide here: https://httptoolkit.com/blog/tls-fingerprinting-node-js/) to recognize that the traffic is coming from software that it's not expecting (i.e. from mitmproxy in this case, not from an Android app).

Different mitm tools often have different TLS fingerprints, which may allow you to work around this, so that's worth investigating. Assuming this is indeed the cause though, this isn't something you can resolve with Frida - it depends completely on the MITM setup that you proxy through.

**Closed by pimterry** 2024-08-03 09:39 UTC

**Comment by pimterry** [comment] 2024-08-04 10:17
Ah, ok, that makes sense. Nonetheless, this is the server rejecting your certs, not the client, so it's not related to these scripts.

This is a configuration issue with your proxy setup. You need to configure mitmproxy to send client certs the way you want. I'm not sure how to do that with mitmproxy so you'll need to talk to them if you're not sure. Alternatively you can also use HTTP Toolkit, which definitely does support client certificates for requests like this (and also automatically manages & runs these Frida scripts for you) as part of [HTTP Toolkit Pro](https://httptoolkit.com/get-pro/).

**Comment by rhysperry111** [comment] 2024-09-06 18:14
Is it within the scope of this repo to at least extract client certificates?

**Comment by pimterry** [comment] 2024-09-09 07:47
> Is it within the scope of this repo to at least extract client certificates?

That would be neat, but it's a bit complicated from a UX perspective within HTTP Toolkit itself. That said, I totally agree a script like that would be useful. If you're interested in working on that, I'd happily accept a PR for it.

**Comment by rhysperry111** [comment] 2024-09-09 09:59
I spent a few hours over the weekend trying it, but having no experience using frida I was shooting blind and didn't get anything worked out. I think I got close a few times but was never able to get it to actually print out the certificate data (and it didn't help that I wasn't 100% sure the app I was messing with was using client certificates)
