### ISSUE TITLE
Add Support for Intercept Flutter

### ISSUE THREAD

**Issue by brunao-br** [httptoolkit/frida-interception-and-unpinning#99] opened 2024-07-03 23:00 UTC
Add Support for intercepting Flutter applications support for changing the port to 8083 to be able to use REflutter (https://github.com/Impact-I/reFlutter/)

**Comment by pimterry** [comment] 2024-07-08 09:30
I'm not really sure what this means @brunao-br, can you explain more? In theory with these existing scripts you can redirect traffic to any port you like (including 8083). The current scripts can't automatically modify certificate settings for Flutter, but if REflutter can do that they using them together should work fine as far as I know.

**Comment by pimterry** [comment] 2024-07-08 15:17
It's possible to change the HTTP Toolkit port in the Pro settings, but not in the free version.

But that's not related to these scripts - you can use these scripts with any tool. It would be helpful if you could explain your problem more clearly and in more detail, including all the current steps you're following, and where exactly it fails.

**Comment by pimterry** [comment] 2024-07-09 10:39
Ok, that sounds like you have everything you need then. Can you explain what the problem is? From my understanding, I think you should be able to:

* Patch the app using Reflutter and then install it
* Intercept using HTTP toolkit (either using the ADB setup with the Android app set to capture traffic to port 8083, or by using the automated Frida setup which always captures all traffic, or by just using Pro to listen on port 8083)
* The Reflutter patch will fix the certificates, and HTTP Toolkit will capture the traffic

What's the problem? Please provide detailed steps and screenshots of any errors or other behaviour. I'm afraid if you can't be more specific about exactly what you're doing and what's going wrong I'm going to have to close this issue.

**Comment by pimterry** [comment] 2024-07-09 14:22
Fair enough! If that works for you then that's totally fine, and gives you more control over what's going on than the other two approaches. I'll close this as resolved for now, but if you're still having issues do please explain more and I'm happy to help.

**Closed by pimterry** 2024-07-09 14:22 UTC
